name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: acquiring secrets
      env:
          ROUTAA_MAVEN_USERNAME: ${{ secrets.ROUTAA_MAVEN_USERNAME }}
          ROUTAA_MAVEN_PASSWORD: ${{ secrets.ROUTAA_MAVEN_PASSWORD }}
      run: echo ROUTAA_MAVEN_USERNAME=\"$ROUTAA_MAVEN_USERNAME\" > ./gradle.properties &&
       echo ROUTAA_MAVEN_PASSWORD=\"$ROUTAA_MAVEN_PASSWORD\" > ./gradle.properties &&
       cat ./gradle.properties
    - name: Build with Gradle
      run: ./gradlew build
